spring:
  datasource:
    url: jdbc:mysql://localhost:3306/l2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: l2
    password: 123456

# 邮件配置
email:
  # 邮件协议
  protocol: smtp
  # 邮件服务器
  host: smtp.qq.com
  # 邮件服务器端口
  port: demo_port
  # 邮件发送者
  account: demo_account
  # 邮件授权码
  password: demo_password
  # 发件人信息
  from-name: L2系统通知
  from-email: l2_notify@yourdomain.com
  # 连接超时时间（毫秒）
  timeout: 10000
  # 启用SSL加密
  ssl-enable: true