server:
  port: 8090
  worker-id: 1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/l2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: l2
    password: 123456

# https://baomidou.com/reference/
mybatis-plus:
  # 指定 MyBatis Mapper 对应的 XML 文件位置。
  mapper-locations: classpath*:/mapper/*.xml
  # 指定 MyBatis 别名包扫描路径，用于给包中的类注册别名。
  type-aliases-package: com.l2.domain
  # MyBatis-Plus 提供的全局策略配置
  global-config:
    # 控制是否在控制台打印 MyBatis-Plus 的 LOGO。
    banner: false

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        context: DEBUG

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.l2.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn